
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - pytorch
  - torchvision
  - torchaudio

  - pip:
      - opencv-python
      - albumentations
      - timm
      - nibabel
      - SimpleITK
      - monai
      - tqdm
      - pillow

